<a href="https://colab.research.google.com/github/harshapsharshaps-netizen/Numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python

#array collection of data with same data type(homogenious)

a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing forward, backward

b=np.array([1,2,3,4,5])

#print 1,2
b[0:2]

#print 5,4
b[-1:-3:-1]

#print 4,5
b[3:]

#print 2,1
b[-4::-1]

array([2, 1])

In [ ]:
#dimension
a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4]])

a.ndim #dimension=1 vector

b.ndim

print(b)

b.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3,4,5

z=np.array([[2,3],[4,5]])

print(z)

print(z.shape)

print(z.ndim)

print(z.size) #total number of elements in a matrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print shape ,size ,dimension

k=np.array([[1,2,3],[4,5,6]])
print(k)
print(k.size)
print(k.ndim)
print(k.shape)

[[1 2 3]
 [4 5 6]]
6
2
(2, 3)


In [ ]:
#crate a 4x2 matrix display its shape size

a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(a[0])
print(a[:,0])
print(a[1,1])
print(a[2,2])

NameError: name 'a' is not defined

In [3]:
print(a[3,2:])
print(a[2:,2:])

NameError: name 'a' is not defined

In [ ]:
print(a[2:,1:3])
print(a[1:3,0:3])
print(a[0:3,1:])
print(a[1:,0:])
print(a[0:,1:2])
print(a[0:,0:])

In [4]:
#zero matrix

import numpy as np
z=np.zeros([3,3])   # 3x3 matrix
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
z=np.zeros([3,3,3])    # 3 3x3 matri
print(z)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
import numpy as np
z=np.zeros([3,3,3],dtype=complex)   # complex - to change datatype into complex
z

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [7]:
import numpy as np
z=np.zeros([2,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [8]:
# one matrix

z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
# create two 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [10]:
#matrix addition
print((a+b))

[[ 4  3]
 [ 9 11]]


In [11]:
#matrix substraction
print((a-b))

[[-2  1]
 [-3 -3]]


In [12]:
#matrix multiplication

#print(a*b)  #not a matrix multiplication

print(a@b)

print(a.dot(b))

[[15 15]
 [33 31]]
[[15 15]
 [33 31]]


In [13]:
#matrix divison

print(a/b)

[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [14]:
# magic
#  _add_ - function starting in underscore
#full matrix   - all elements are same

z=np.full([3,3],5,dtype=int)
z

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
#create 3x4 matrix with value 9 and datatype complex
z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [16]:
#identity matrix

z=np.identity(3,dtype=int)
z
#or
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# create a 4x4 matrix

y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)
print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [18]:
a=y.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [19]:
# arange
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [20]:
# create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
# create a 3x3 matrix with float values

a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.1, 2.5, 7.1]])

In [22]:
# Floor

z=np.floor(a)
z

array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 2., 7.]])

In [23]:
# Ceil
z=np.ceil(a)
z

array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 3., 8.]])

In [24]:
# round
z=np.round(a)
z

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [32]:
# create a 3x3 matrix

a=np.arange(1,10).reshape(3,3)
print(a)

print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))

print(a.sum())

print(a.sum(axis=1))

print(a.sum(axis=0))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]
45
[ 6 15 24]
[12 15 18]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [33]:
print(np.sqrt(a))

print(np.sin(a))

print(np.tan(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [34]:
#flatten

a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#sort
#create 3x3 matrix

a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)
b=np.sort(a,axis=1)
print(b)

c=np.argsort(a,axis=1)
print(c)



[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[1 3 4]
 [1 3 5]
 [6 8 9]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
